### ISSUE TITLE
Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 964 column 3

### ISSUE THREAD

**Issue by HIT-leaderone** [BradyFU/Woodpecker#14]
```
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
final text_encoder_type: bert-base-uncased
FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
val_model_path= Salesforce/blip2-flan-t5-xxl
Traceback (most recent call last):
  File "/home/ubuntu/DPO/woodpecker/Woodpecker/inference.py", line 39, in <module>
    corrector = Corrector(model_args)
  File "/home/ubuntu/DPO/woodpecker/Woodpecker/vis_corrector.py", line 20, in __init__
    self.answerer = Answerer(args)
  File "/home/ubuntu/DPO/woodpecker/Woodpecker/models/answerer.py", line 67, in __init__
    self.processor = Blip2Processor.from_pretrained(val_model_path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/processing_utils.py", line 184, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/processing_utils.py", line 228, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 693, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1812, in from_pretrained
    return cls._from_pretrained(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1975, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5_fast.py", line 133, in __init__
    super().__init__(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 964 column 3
```

We try to update tokenizers and transformers to solve this issue. But another issue occurs in grounding dino as follows:
```
  File "/home/ubuntu/DPO/woodpecker/Woodpecker/inference.py", line 1, in <module>
    from vis_corrector import Corrector
  File "/home/ubuntu/DPO/woodpecker/Woodpecker/vis_corrector.py", line 3, in <module>
    from models.detector import Detector
  File "/home/ubuntu/DPO/woodpecker/Woodpecker/models/detector.py", line 12, in <module>
    from groundingdino.util.inference import load_model, load_image, predict
  File "/home/ubuntu/DPO/segment-anything-2/GroundingDINO/groundingdino/util/inference.py", line 12, in <module>
    from groundingdino.models import build_model
  File "/home/ubuntu/DPO/segment-anything-2/GroundingDINO/groundingdino/models/__init__.py", line 8, in <module>
    from .GroundingDINO import build_groundingdino
  File "/home/ubuntu/DPO/segment-anything-2/GroundingDINO/groundingdino/models/GroundingDINO/__init__.py", line 15, in <module>
    from .groundingdino import build_groundingdino
  File "/home/ubuntu/DPO/segment-anything-2/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 24, in <module>
    from transformers import AutoTokenizer, BertModel, BertTokenizer, RobertaModel, RobertaTokenizerFast
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/utils/__init__.py", line 37, in <module>
    from .generic import (
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/utils/generic.py", line 475, in <module>
    _torch_pytree.register_pytree_node(
AttributeError: module 'torch.utils._pytree' has no attribute 'register_pytree_node'. Did you mean: '_register_pytree_node'?
```

**Comment by HIT-leaderone** [comment]
Update torch to 2.X and then update tokenizers and transformers can solve this issue.

**Comment by xjtupanda** [comment]
Glad to hear the problem solved :)
